### ISSUE TITLE
Train intent does not work

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/almond-dialog-agent#27]
Almond Says: Sorry, I had an error processing your command: false == true
AssertionError [ERR_ASSERTION]: false == true
    at Dispatcher.handle (/home/gcampagn/mobisocial/almond-gnome/service/node_modules/almond-dialog-agent/lib/dispatcher.js:464:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by gcampax** [comment]
I cannot reproduce this issue, and we have tests that cover this code and ensure we can use Train successfully, so I'm going to close this.
